name: Build Master

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Master
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint Project
        run: yarn lint

      - name: Build Project
        run: yarn build
