name: Test Runner

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [master]

jobs:
  build-test-enironment:
    name: Build Test Environment
    runs-on: ubuntu-latest
    environment: Production
    env:
      COMPOSE_FILE: docker-compose.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compose Docker Container
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Install Dependencies
        run: npm install --frozen-lockfile

      - name: Lint Project
        run: npm run lint

      - name: Build Project
        run: npm run build

      - name: Run Tests
        run: npm run test

      - name: Compose Down Docker Container
        run: docker-compose -f "docker-compose.yml" down
